@startuml "casos_uso"
skinparam monochrome true
skinparam shadowing false
left to right direction

actor "Visitante" as Visitante
actor "Usuario Registrado" as Usuario
actor "Administrador" as Admin

rectangle "Plataforma Patitas Home" {
  
  ' Casos de uso de Visitante
  usecase "Explorar Feed de Mascotas" as UC_Explorar
  usecase "Registrarse en el Sistema" as UC_Registro
  
  ' Casos de uso de Usuario Registrado
  usecase "Iniciar Sesión" as UC_Login
  usecase "Reportar Mascota Perdida" as UC_Perdida
  usecase "Reportar Mascota Encontrada" as UC_Encontrada
  usecase "Publicar Perfil de Adopción" as UC_Adopcion
  usecase "Interactuar (Comentar/Reaccionar)" as UC_Interaccion
  usecase "Gestionar Mensajería Privada" as UC_Chat
  
  ' Casos de uso de Administrador
  usecase "Moderar Contenido y Publicaciones" as UC_Moderar
  usecase "Gestionar Accesos de Usuarios" as UC_Usuarios
}

' Relaciones Visitante
Visitante --> UC_Explorar
Visitante --> UC_Registro

' Relaciones Usuario Registrado (Hereda acceso al feed)
Usuario --> UC_Explorar
Usuario --> UC_Perdida
Usuario --> UC_Encontrada
Usuario --> UC_Adopcion
Usuario --> UC_Interaccion
Usuario --> UC_Chat

' Relaciones Administrador
Admin --> UC_Moderar
Admin --> UC_Usuarios

UC_Perdida ...> UC_Login : <<include>>
UC_Encontrada ...> UC_Login : <<include>>
UC_Adopcion ...> UC_Login : <<include>>
UC_Interaccion ...> UC_Login : <<include>>
UC_Chat ...> UC_Login : <<include>>
UC_Moderar ...> UC_Login : <<include>>
UC_Usuarios ...> UC_Login : <<include>>



@enduml