@startuml "actividades_03"
skinparam monochrome true
skinparam shadowing false

title Reporte de Mascota Encontrada

start
:Seleccionar módulo "Mascota Encontrada";
:Ingresar características físicas\n(Especie, Raza, Color, Tamaño aproximado);

repeat
  :Adjuntar fotografía del animal encontrado;
backward: Notificar error (Formato o peso excedido);
repeat while (¿Fotografía válida?) is (No)
->Sí;

:Indicar ubicación exacta del hallazgo y fecha;
:Definir estado de resguardo actual;
:Proporcionar datos de contacto del rescatista temporal;
:Confirmar publicación;

partition "Procesamiento interno" {
  :Almacenar registro en base de datos;
  :Buscar coincidencias;
  
  if (¿Existen posibles coincidencias?) then (Sí)
    :Generar notificación automática\na los dueños de mascotas similares;
  else (No)
  endif
}

:Desplegar reporte en el feed general;
stop
@enduml