# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"Y\n\nUserClaims\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x10\n\x08is_valid\x18\x04 \x01(\x08\x12\x0b\n\x03\x65xp\x18\x05 \x01(\x03\"%\n\x12GetUserByIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"g\n\x0bUserProfile\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x17\n\x0fnombre_completo\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\"1\n\x10\x43heckRoleRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"%\n\x11\x43heckRoleResponse\x12\x10\n\x08has_role\x18\x01 \x01(\x08\x32\xc6\x01\n\x0b\x41uthService\x12=\n\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x10.auth.UserClaims\x12:\n\x0bGetUserById\x12\x18.auth.GetUserByIdRequest\x1a\x11.auth.UserProfile\x12<\n\tCheckRole\x12\x16.auth.CheckRoleRequest\x1a\x17.auth.CheckRoleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATETOKENREQUEST']._serialized_start=20
  _globals['_VALIDATETOKENREQUEST']._serialized_end=57
  _globals['_USERCLAIMS']._serialized_start=59
  _globals['_USERCLAIMS']._serialized_end=148
  _globals['_GETUSERBYIDREQUEST']._serialized_start=150
  _globals['_GETUSERBYIDREQUEST']._serialized_end=187
  _globals['_USERPROFILE']._serialized_start=189
  _globals['_USERPROFILE']._serialized_end=292
  _globals['_CHECKROLEREQUEST']._serialized_start=294
  _globals['_CHECKROLEREQUEST']._serialized_end=343
  _globals['_CHECKROLERESPONSE']._serialized_start=345
  _globals['_CHECKROLERESPONSE']._serialized_end=382
  _globals['_AUTHSERVICE']._serialized_start=385
  _globals['_AUTHSERVICE']._serialized_end=583
# @@protoc_insertion_point(module_scope)
