# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calificaciones.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calificaciones.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63\x61lificaciones.proto\x12\x0e\x63\x61lificaciones\"+\n\x15GetConcentradoRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\t\"\x91\x01\n\x0b\x41lumnoCalif\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x11\n\tmatricula\x18\x02 \x01(\t\x12\x17\n\x0fnombre_completo\x18\x03 \x01(\t\x12\x15\n\rpromedio_real\x18\x04 \x01(\x02\x12\x1b\n\x13promedio_redondeado\x18\x05 \x01(\x05\x12\x0f\n\x07\x65status\x18\x06 \x01(\t\"F\n\x16GetConcentradoResponse\x12,\n\x07\x61lumnos\x18\x01 \x03(\x0b\x32\x1b.calificaciones.AlumnoCalif\"A\n\x18GetPromedioAlumnoRequest\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x12\n\nmateria_id\x18\x02 \x01(\t\"v\n\x19GetPromedioAlumnoResponse\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x12\n\nmateria_id\x18\x02 \x01(\t\x12\x15\n\rpromedio_real\x18\x03 \x01(\x02\x12\x1b\n\x13promedio_redondeado\x18\x04 \x01(\x05\"3\n\x1dGetEstadisticasMateriaRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\t\"\xd8\x01\n\x1eGetEstadisticasMateriaResponse\x12\x12\n\nmateria_id\x18\x01 \x01(\t\x12\x15\n\rtotal_alumnos\x18\x02 \x01(\x05\x12\x11\n\taprobados\x18\x03 \x01(\x05\x12\x12\n\nreprobados\x18\x04 \x01(\x05\x12\x11\n\ten_riesgo\x18\x05 \x01(\x05\x12\x17\n\x0fpromedio_grupal\x18\x06 \x01(\x02\x12\x1b\n\x13\x63\x61lificacion_maxima\x18\x07 \x01(\x02\x12\x1b\n\x13\x63\x61lificacion_minima\x18\x08 \x01(\x02\x32\xdb\x02\n\x15\x43\x61lificacionesService\x12_\n\x0eGetConcentrado\x12%.calificaciones.GetConcentradoRequest\x1a&.calificaciones.GetConcentradoResponse\x12h\n\x11GetPromedioAlumno\x12(.calificaciones.GetPromedioAlumnoRequest\x1a).calificaciones.GetPromedioAlumnoResponse\x12w\n\x16GetEstadisticasMateria\x12-.calificaciones.GetEstadisticasMateriaRequest\x1a..calificaciones.GetEstadisticasMateriaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calificaciones_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCONCENTRADOREQUEST']._serialized_start=40
  _globals['_GETCONCENTRADOREQUEST']._serialized_end=83
  _globals['_ALUMNOCALIF']._serialized_start=86
  _globals['_ALUMNOCALIF']._serialized_end=231
  _globals['_GETCONCENTRADORESPONSE']._serialized_start=233
  _globals['_GETCONCENTRADORESPONSE']._serialized_end=303
  _globals['_GETPROMEDIOALUMNOREQUEST']._serialized_start=305
  _globals['_GETPROMEDIOALUMNOREQUEST']._serialized_end=370
  _globals['_GETPROMEDIOALUMNORESPONSE']._serialized_start=372
  _globals['_GETPROMEDIOALUMNORESPONSE']._serialized_end=490
  _globals['_GETESTADISTICASMATERIAREQUEST']._serialized_start=492
  _globals['_GETESTADISTICASMATERIAREQUEST']._serialized_end=543
  _globals['_GETESTADISTICASMATERIARESPONSE']._serialized_start=546
  _globals['_GETESTADISTICASMATERIARESPONSE']._serialized_end=762
  _globals['_CALIFICACIONESSERVICE']._serialized_start=765
  _globals['_CALIFICACIONESSERVICE']._serialized_end=1112
# @@protoc_insertion_point(module_scope)
