# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import alumnos_pb2 as alumnos__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in alumnos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlumnosServiceStub(object):
    """Servicio gRPC del MS-3 Docentes & Alumnos
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAlumnosByMateria = channel.unary_unary(
                '/alumnos.AlumnosService/GetAlumnosByMateria',
                request_serializer=alumnos__pb2.GetAlumnosByMateriaRequest.SerializeToString,
                response_deserializer=alumnos__pb2.AlumnosList.FromString,
                _registered_method=True)
        self.GetAlumnoById = channel.unary_unary(
                '/alumnos.AlumnosService/GetAlumnoById',
                request_serializer=alumnos__pb2.GetAlumnoByIdRequest.SerializeToString,
                response_deserializer=alumnos__pb2.AlumnoInfo.FromString,
                _registered_method=True)
        self.IsAlumnoEnMateria = channel.unary_unary(
                '/alumnos.AlumnosService/IsAlumnoEnMateria',
                request_serializer=alumnos__pb2.IsAlumnoEnMateriaRequest.SerializeToString,
                response_deserializer=alumnos__pb2.IsAlumnoEnMateriaResponse.FromString,
                _registered_method=True)


class AlumnosServiceServicer(object):
    """Servicio gRPC del MS-3 Docentes & Alumnos
    """

    def GetAlumnosByMateria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlumnoById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsAlumnoEnMateria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlumnosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAlumnosByMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlumnosByMateria,
                    request_deserializer=alumnos__pb2.GetAlumnosByMateriaRequest.FromString,
                    response_serializer=alumnos__pb2.AlumnosList.SerializeToString,
            ),
            'GetAlumnoById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlumnoById,
                    request_deserializer=alumnos__pb2.GetAlumnoByIdRequest.FromString,
                    response_serializer=alumnos__pb2.AlumnoInfo.SerializeToString,
            ),
            'IsAlumnoEnMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.IsAlumnoEnMateria,
                    request_deserializer=alumnos__pb2.IsAlumnoEnMateriaRequest.FromString,
                    response_serializer=alumnos__pb2.IsAlumnoEnMateriaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alumnos.AlumnosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('alumnos.AlumnosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlumnosService(object):
    """Servicio gRPC del MS-3 Docentes & Alumnos
    """

    @staticmethod
    def GetAlumnosByMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alumnos.AlumnosService/GetAlumnosByMateria',
            alumnos__pb2.GetAlumnosByMateriaRequest.SerializeToString,
            alumnos__pb2.AlumnosList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlumnoById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alumnos.AlumnosService/GetAlumnoById',
            alumnos__pb2.GetAlumnoByIdRequest.SerializeToString,
            alumnos__pb2.AlumnoInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsAlumnoEnMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alumnos.AlumnosService/IsAlumnoEnMateria',
            alumnos__pb2.IsAlumnoEnMateriaRequest.SerializeToString,
            alumnos__pb2.IsAlumnoEnMateriaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
