# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alumnos.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'alumnos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ralumnos.proto\x12\x07\x61lumnos\"0\n\x1aGetAlumnosByMateriaRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\t\"\x8e\x01\n\nAlumnoInfo\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x11\n\tmatricula\x18\x02 \x01(\t\x12\x17\n\x0fnombre_completo\x18\x03 \x01(\t\x12\x0e\n\x06\x63orreo\x18\x04 \x01(\t\x12\x16\n\x0etipo_formacion\x18\x05 \x01(\t\x12\x19\n\x11\x61\x63tivo_en_materia\x18\x06 \x01(\x08\"3\n\x0b\x41lumnosList\x12$\n\x07\x61lumnos\x18\x01 \x03(\x0b\x32\x13.alumnos.AlumnoInfo\")\n\x14GetAlumnoByIdRequest\x12\x11\n\talumno_id\x18\x01 \x01(\t\"A\n\x18IsAlumnoEnMateriaRequest\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x12\n\nmateria_id\x18\x02 \x01(\t\"C\n\x19IsAlumnoEnMateriaResponse\x12\x10\n\x08inscrito\x18\x01 \x01(\x08\x12\x14\n\x0c\x64\x61\x64o_de_baja\x18\x02 \x01(\x08\x32\x83\x02\n\x0e\x41lumnosService\x12P\n\x13GetAlumnosByMateria\x12#.alumnos.GetAlumnosByMateriaRequest\x1a\x14.alumnos.AlumnosList\x12\x43\n\rGetAlumnoById\x12\x1d.alumnos.GetAlumnoByIdRequest\x1a\x13.alumnos.AlumnoInfo\x12Z\n\x11IsAlumnoEnMateria\x12!.alumnos.IsAlumnoEnMateriaRequest\x1a\".alumnos.IsAlumnoEnMateriaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alumnos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETALUMNOSBYMATERIAREQUEST']._serialized_start=26
  _globals['_GETALUMNOSBYMATERIAREQUEST']._serialized_end=74
  _globals['_ALUMNOINFO']._serialized_start=77
  _globals['_ALUMNOINFO']._serialized_end=219
  _globals['_ALUMNOSLIST']._serialized_start=221
  _globals['_ALUMNOSLIST']._serialized_end=272
  _globals['_GETALUMNOBYIDREQUEST']._serialized_start=274
  _globals['_GETALUMNOBYIDREQUEST']._serialized_end=315
  _globals['_ISALUMNOENMATERIAREQUEST']._serialized_start=317
  _globals['_ISALUMNOENMATERIAREQUEST']._serialized_end=382
  _globals['_ISALUMNOENMATERIARESPONSE']._serialized_start=384
  _globals['_ISALUMNOENMATERIARESPONSE']._serialized_end=451
  _globals['_ALUMNOSSERVICE']._serialized_start=454
  _globals['_ALUMNOSSERVICE']._serialized_end=713
# @@protoc_insertion_point(module_scope)
