# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notificaciones.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'notificaciones.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14notificaciones.proto\x12\x0enotificaciones\"S\n\x15SendBienvenidaRequest\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x12\n\nmateria_id\x18\x02 \x01(\t\x12\x13\n\x0b\x63lave_unica\x18\x03 \x01(\t\"L\n\x0fSendBajaRequest\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x12\n\ndocente_id\x18\x02 \x01(\t\x12\x12\n\nmateria_id\x18\x03 \x01(\t\".\n\x18SendCierreMateriaRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\t\"?\n\x18SendResetPasswordRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nreset_link\x18\x02 \x01(\t\"I\n\x0cSendResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x0fnotificacion_id\x18\x03 \x01(\t2\xf8\x02\n\x15NotificacionesService\x12U\n\x0eSendBienvenida\x12%.notificaciones.SendBienvenidaRequest\x1a\x1c.notificaciones.SendResponse\x12N\n\rSendBajaNotif\x12\x1f.notificaciones.SendBajaRequest\x1a\x1c.notificaciones.SendResponse\x12[\n\x11SendCierreMateria\x12(.notificaciones.SendCierreMateriaRequest\x1a\x1c.notificaciones.SendResponse\x12[\n\x11SendResetPassword\x12(.notificaciones.SendResetPasswordRequest\x1a\x1c.notificaciones.SendResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notificaciones_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDBIENVENIDAREQUEST']._serialized_start=40
  _globals['_SENDBIENVENIDAREQUEST']._serialized_end=123
  _globals['_SENDBAJAREQUEST']._serialized_start=125
  _globals['_SENDBAJAREQUEST']._serialized_end=201
  _globals['_SENDCIERREMATERIAREQUEST']._serialized_start=203
  _globals['_SENDCIERREMATERIAREQUEST']._serialized_end=249
  _globals['_SENDRESETPASSWORDREQUEST']._serialized_start=251
  _globals['_SENDRESETPASSWORDREQUEST']._serialized_end=314
  _globals['_SENDRESPONSE']._serialized_start=316
  _globals['_SENDRESPONSE']._serialized_end=389
  _globals['_NOTIFICACIONESSERVICE']._serialized_start=392
  _globals['_NOTIFICACIONESSERVICE']._serialized_end=768
# @@protoc_insertion_point(module_scope)
