# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: periodos.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'periodos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eperiodos.proto\x12\x08periodos\"\x0e\n\x0c\x45mptyRequest\"+\n\x15GetMateriaByIdRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\t\"\xa7\x01\n\x0bMateriaInfo\x12\x12\n\nmateria_id\x18\x01 \x01(\t\x12\x0b\n\x03nrc\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x0f\n\x07seccion\x18\x04 \x01(\t\x12\r\n\x05\x63lave\x18\x05 \x01(\t\x12\x12\n\ndocente_id\x18\x06 \x01(\t\x12\x0f\n\x07horario\x18\x07 \x01(\t\x12\x12\n\nperiodo_id\x18\x08 \x01(\t\x12\x0e\n\x06\x65stado\x18\t \x01(\t\"E\n\x1bGetMateriasByDocenteRequest\x12\x12\n\ndocente_id\x18\x01 \x01(\t\x12\x12\n\nperiodo_id\x18\x02 \x01(\t\"7\n\x0cMateriasList\x12\'\n\x08materias\x18\x01 \x03(\x0b\x32\x15.periodos.MateriaInfo\"\x81\x01\n\x0bPeriodoInfo\x12\x12\n\nperiodo_id\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x14\n\x0c\x66\x65\x63ha_inicio\x18\x03 \x01(\t\x12\x11\n\tfecha_fin\x18\x04 \x01(\t\x12\x15\n\rplan_estudios\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tivo\x18\x06 \x01(\x08\x32\xf5\x01\n\x0fPeriodosService\x12H\n\x0eGetMateriaById\x12\x1f.periodos.GetMateriaByIdRequest\x1a\x15.periodos.MateriaInfo\x12U\n\x14GetMateriasByDocente\x12%.periodos.GetMateriasByDocenteRequest\x1a\x16.periodos.MateriasList\x12\x41\n\x10GetPeriodoActivo\x12\x16.periodos.EmptyRequest\x1a\x15.periodos.PeriodoInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'periodos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=28
  _globals['_EMPTYREQUEST']._serialized_end=42
  _globals['_GETMATERIABYIDREQUEST']._serialized_start=44
  _globals['_GETMATERIABYIDREQUEST']._serialized_end=87
  _globals['_MATERIAINFO']._serialized_start=90
  _globals['_MATERIAINFO']._serialized_end=257
  _globals['_GETMATERIASBYDOCENTEREQUEST']._serialized_start=259
  _globals['_GETMATERIASBYDOCENTEREQUEST']._serialized_end=328
  _globals['_MATERIASLIST']._serialized_start=330
  _globals['_MATERIASLIST']._serialized_end=385
  _globals['_PERIODOINFO']._serialized_start=388
  _globals['_PERIODOINFO']._serialized_end=517
  _globals['_PERIODOSSERVICE']._serialized_start=520
  _globals['_PERIODOSSERVICE']._serialized_end=765
# @@protoc_insertion_point(module_scope)
