# Generated by Django 5.1.3 on 2026-05-06 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('tipo_formacion', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alumnos',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionMateria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('materia_id', models.CharField(max_length=64)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('dado_de_baja', models.BooleanField(default=False)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='alumnos.alumno')),
            ],
            options={
                'db_table': 'inscripciones_materia',
                'indexes': [models.Index(fields=['materia_id'], name='inscripcion_materia_ac89aa_idx'), models.Index(fields=['materia_id', 'dado_de_baja'], name='inscripcion_materia_7bed80_idx')],
                'unique_together': {('alumno', 'materia_id')},
            },
        ),
    ]
