# Generated by Django 5.1.3 on 2026-05-07 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CALIFICACIONES', 'Calificaciones finales'), ('ASISTENCIAS', 'Concentrado de asistencias')], max_length=20)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('XLS', 'Excel (XLS)'), ('XLSX', 'Excel (XLSX)')], max_length=5)),
                ('materia_id', models.CharField(max_length=64)),
                ('generado_por_user_id', models.CharField(max_length=64)),
                ('file_name', models.CharField(max_length=255)),
                ('size_bytes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reportes_generados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['materia_id', 'tipo'], name='reportes_ge_materia_6e45b0_idx'), models.Index(fields=['generado_por_user_id'], name='reportes_ge_generad_876dd5_idx')],
            },
        ),
    ]
