# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asistencias.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'asistencias.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61sistencias.proto\x12\x0b\x61sistencias\"C\n\x1aGetAsistenciaAlumnoRequest\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x12\n\nmateria_id\x18\x02 \x01(\t\"U\n\nAsistencia\x12\x15\n\rasistencia_id\x18\x01 \x01(\t\x12\r\n\x05\x66\x65\x63ha\x18\x02 \x01(\t\x12\x0e\n\x06\x65stado\x18\x03 \x01(\t\x12\x11\n\tsesion_id\x18\x04 \x01(\t\"?\n\x0f\x41sistenciasList\x12,\n\x0b\x61sistencias\x18\x01 \x03(\x0b\x32\x17.asistencias.Asistencia\"6\n GetEstadisticasAsistenciaRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\t\"\xaf\x01\n\x16\x45stadisticasAsistencia\x12\x12\n\nmateria_id\x18\x01 \x01(\t\x12\x16\n\x0etotal_sesiones\x18\x02 \x01(\x05\x12\x19\n\x11total_asistencias\x18\x03 \x01(\x05\x12\x16\n\x0etotal_retardos\x18\x04 \x01(\x05\x12\x17\n\x0ftotal_ausencias\x18\x05 \x01(\x05\x12\x1d\n\x15porcentaje_asistencia\x18\x06 \x01(\x02\x32\xe3\x01\n\x12\x41sistenciasService\x12\\\n\x13GetAsistenciaAlumno\x12\'.asistencias.GetAsistenciaAlumnoRequest\x1a\x1c.asistencias.AsistenciasList\x12o\n\x19GetEstadisticasAsistencia\x12-.asistencias.GetEstadisticasAsistenciaRequest\x1a#.asistencias.EstadisticasAsistenciab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asistencias_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETASISTENCIAALUMNOREQUEST']._serialized_start=34
  _globals['_GETASISTENCIAALUMNOREQUEST']._serialized_end=101
  _globals['_ASISTENCIA']._serialized_start=103
  _globals['_ASISTENCIA']._serialized_end=188
  _globals['_ASISTENCIASLIST']._serialized_start=190
  _globals['_ASISTENCIASLIST']._serialized_end=253
  _globals['_GETESTADISTICASASISTENCIAREQUEST']._serialized_start=255
  _globals['_GETESTADISTICASASISTENCIAREQUEST']._serialized_end=309
  _globals['_ESTADISTICASASISTENCIA']._serialized_start=312
  _globals['_ESTADISTICASASISTENCIA']._serialized_end=487
  _globals['_ASISTENCIASSERVICE']._serialized_start=490
  _globals['_ASISTENCIASSERVICE']._serialized_end=717
# @@protoc_insertion_point(module_scope)
