# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import periodos_pb2 as periodos__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in periodos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeriodosServiceStub(object):
    """Servicio gRPC del MS-2 Periodos & Materias
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMateriaById = channel.unary_unary(
                '/periodos.PeriodosService/GetMateriaById',
                request_serializer=periodos__pb2.GetMateriaByIdRequest.SerializeToString,
                response_deserializer=periodos__pb2.MateriaInfo.FromString,
                _registered_method=True)
        self.GetMateriasByDocente = channel.unary_unary(
                '/periodos.PeriodosService/GetMateriasByDocente',
                request_serializer=periodos__pb2.GetMateriasByDocenteRequest.SerializeToString,
                response_deserializer=periodos__pb2.MateriasList.FromString,
                _registered_method=True)
        self.GetPeriodoActivo = channel.unary_unary(
                '/periodos.PeriodosService/GetPeriodoActivo',
                request_serializer=periodos__pb2.EmptyRequest.SerializeToString,
                response_deserializer=periodos__pb2.PeriodoInfo.FromString,
                _registered_method=True)


class PeriodosServiceServicer(object):
    """Servicio gRPC del MS-2 Periodos & Materias
    """

    def GetMateriaById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMateriasByDocente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeriodoActivo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeriodosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMateriaById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMateriaById,
                    request_deserializer=periodos__pb2.GetMateriaByIdRequest.FromString,
                    response_serializer=periodos__pb2.MateriaInfo.SerializeToString,
            ),
            'GetMateriasByDocente': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMateriasByDocente,
                    request_deserializer=periodos__pb2.GetMateriasByDocenteRequest.FromString,
                    response_serializer=periodos__pb2.MateriasList.SerializeToString,
            ),
            'GetPeriodoActivo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeriodoActivo,
                    request_deserializer=periodos__pb2.EmptyRequest.FromString,
                    response_serializer=periodos__pb2.PeriodoInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'periodos.PeriodosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('periodos.PeriodosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeriodosService(object):
    """Servicio gRPC del MS-2 Periodos & Materias
    """

    @staticmethod
    def GetMateriaById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/periodos.PeriodosService/GetMateriaById',
            periodos__pb2.GetMateriaByIdRequest.SerializeToString,
            periodos__pb2.MateriaInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMateriasByDocente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/periodos.PeriodosService/GetMateriasByDocente',
            periodos__pb2.GetMateriasByDocenteRequest.SerializeToString,
            periodos__pb2.MateriasList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeriodoActivo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/periodos.PeriodosService/GetPeriodoActivo',
            periodos__pb2.EmptyRequest.SerializeToString,
            periodos__pb2.PeriodoInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
