# Generated by Django 5.1.3 on 2026-05-07 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaPeriodo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('docente_id', models.CharField(max_length=64)),
                ('periodo_id', models.CharField(max_length=64)),
                ('materia_id', models.CharField(max_length=64)),
                ('total_alumnos', models.IntegerField(default=0)),
                ('aprobados', models.IntegerField(default=0)),
                ('reprobados', models.IntegerField(default=0)),
                ('promedio_grupal', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_asistencia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('snapshot_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estadisticas_periodo',
                'indexes': [models.Index(fields=['docente_id', 'periodo_id'], name='estadistica_docente_5d787a_idx'), models.Index(fields=['materia_id'], name='estadistica_materia_35f149_idx')],
                'unique_together': {('docente_id', 'periodo_id', 'materia_id')},
            },
        ),
    ]
