# Generated by Django 5.1.3 on 2026-05-08 22:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('BIENVENIDA', 'Bienvenida con clave única'), ('BAJA', 'Aviso de baja al docente'), ('CIERRE_MATERIA', 'Cierre de materia'), ('RESET_PASSWORD', 'Recuperación de contraseña')], max_length=20)),
                ('destinatario_email', models.EmailField(max_length=254)),
                ('destinatario_user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('asunto', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('cuerpo_html', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('intentos', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipo', 'estado'], name='notificacio_tipo_de4da0_idx'), models.Index(fields=['destinatario_email'], name='notificacio_destina_41dc80_idx'), models.Index(fields=['-created_at'], name='notificacio_created_10fc1f_idx')],
            },
        ),
    ]
