# Generated by Django 6.0.5 on 2026-05-09 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ponderaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('valor_maximo', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ponderacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='ponderaciones.ponderacion')),
            ],
            options={
                'db_table': 'actividades',
                'ordering': ['fecha', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alumno_id', models.CharField(max_length=64)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='calificaciones.actividad')),
            ],
            options={
                'db_table': 'calificaciones',
                'indexes': [models.Index(fields=['alumno_id'], name='calificacio_alumno__fa1b26_idx'), models.Index(fields=['actividad', 'alumno_id'], name='calificacio_activid_60b434_idx')],
                'unique_together': {('actividad', 'alumno_id')},
            },
        ),
    ]
