# Generated by Django 5.1.3 on 2026-05-02 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=10)),
                ('clave', models.CharField(max_length=20)),
                ('horario', models.CharField(max_length=255)),
                ('docente_id', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('FINALIZADA', 'Finalizada (lista impresa)')], default='ABIERTA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='periodos.periodo')),
            ],
            options={
                'db_table': 'materias',
                'indexes': [models.Index(fields=['docente_id'], name='materias_docente_742a1f_idx'), models.Index(fields=['periodo', 'estado'], name='materias_periodo_f88b46_idx')],
                'unique_together': {('periodo', 'nrc', 'seccion')},
            },
        ),
    ]
