# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reportes.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'reportes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ereportes.proto\x12\x08reportes\"J\n\x15GenerateReportRequest\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\x0f\n\x07\x66ormato\x18\x02 \x01(\t\x12\x12\n\nmateria_id\x18\x03 \x01(\t\"H\n\x0c\x46ileResponse\x12\x12\n\nfile_bytes\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x11\n\tmime_type\x18\x03 \x01(\t\"0\n\x1aGetHistorialDocenteRequest\x12\x12\n\ndocente_id\x18\x01 \x01(\t\"\xb5\x01\n\x0cStatsPeriodo\x12\x12\n\nperiodo_id\x18\x01 \x01(\t\x12\x16\n\x0eperiodo_nombre\x18\x02 \x01(\t\x12\x12\n\nmateria_id\x18\x03 \x01(\t\x12\x16\n\x0emateria_nombre\x18\x04 \x01(\t\x12\x15\n\rtotal_alumnos\x18\x05 \x01(\x05\x12\x17\n\x0fpromedio_grupal\x18\x06 \x01(\x02\x12\x1d\n\x15porcentaje_asistencia\x18\x07 \x01(\x02\">\n\x11HistorialResponse\x12)\n\thistorial\x18\x01 \x03(\x0b\x32\x16.reportes.StatsPeriodo2\xb6\x01\n\x0fReportesService\x12I\n\x0eGenerateReport\x12\x1f.reportes.GenerateReportRequest\x1a\x16.reportes.FileResponse\x12X\n\x13GetHistorialDocente\x12$.reportes.GetHistorialDocenteRequest\x1a\x1b.reportes.HistorialResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reportes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREPORTREQUEST']._serialized_start=28
  _globals['_GENERATEREPORTREQUEST']._serialized_end=102
  _globals['_FILERESPONSE']._serialized_start=104
  _globals['_FILERESPONSE']._serialized_end=176
  _globals['_GETHISTORIALDOCENTEREQUEST']._serialized_start=178
  _globals['_GETHISTORIALDOCENTEREQUEST']._serialized_end=226
  _globals['_STATSPERIODO']._serialized_start=229
  _globals['_STATSPERIODO']._serialized_end=410
  _globals['_HISTORIALRESPONSE']._serialized_start=412
  _globals['_HISTORIALRESPONSE']._serialized_end=474
  _globals['_REPORTESSERVICE']._serialized_start=477
  _globals['_REPORTESSERVICE']._serialized_end=659
# @@protoc_insertion_point(module_scope)
