# Generated by Django 6.0.5 on 2026-05-09 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponderacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('materia_id', models.CharField(max_length=64)),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ponderaciones',
                'indexes': [models.Index(fields=['materia_id'], name='ponderacion_materia_21d7a3_idx')],
                'unique_together': {('materia_id', 'nombre')},
            },
        ),
    ]
